# Generated by Django 4.1.7 on 2024-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_car_image_alter_myuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_photos'),
        ),
    ]
